In [1]:
from SimpleNumpy import *
import numpy as np

In [2]:
test()

hello world!


In [3]:
a = np.array([[1,2,3],[2,4,6]])
b = np.array([[5,6,7],[8,9,10]])

In [4]:
c = sub_val(a,1)
print(c)

[[0. 1. 2.]
 [1. 3. 5.]]


In [5]:
d = plus_arr(c,b)
print(d)

[[ 5.  7.  9.]
 [ 9. 12. 15.]]


In [9]:
f = repeat(d,[0,2,3],5)
print(f)

[[[ 5.  7.  9.]
  [ 9. 12. 15.]]

 [[ 5.  7.  9.]
  [ 9. 12. 15.]]

 [[ 5.  7.  9.]
  [ 9. 12. 15.]]

 [[ 5.  7.  9.]
  [ 9. 12. 15.]]

 [[ 5.  7.  9.]
  [ 9. 12. 15.]]]
